#
# Personal preferences
#
set -o vi
export EDITOR=vi

#
# git prompt
#
GIT_PROMPT_ONLY_IN_REPO=1
source ~/.bash-git-prompt/gitprompt.sh

#
# Append to history continously
#
export HISTTIMEFORMAT="%d/%m/%Y %T "
export PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

#
# https://brew.sh
#
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
HOMEBREW_PREFIX="$(brew --prefix)"
[[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]] && source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
if type brew &>/dev/null
then
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  fi
  for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
  do
    [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
  done
fi

#
# pip3 path
#
export PATH=$PATH:$HOME/.local/bin
